### PR TITLE
Basic set up of the server

### PR DESCRIPTION
**Pull request by Behnazz**

### CODE REVIEW

**Review by MHDGhanemBalhawan — DISMISSED** [review]

**Review by fentonfentonfenton — APPROVED** [review]
I was able to clone this branch, `npm install`and then `npm start`. When I did a `GET` to `:3000/home` - express respond to the message in the router.

👍

**Comment by dahfool** [comment]
@MHDGhanemBalhawan There are 2 PRs the other one is to add react create app https://github.com/CodeYourFuture/events-calender/pull/1

**Review by fentonfentonfenton — CHANGES_REQUESTED** [review]
Suggested
```
app.listen(process.env.PORT || 3001, function () {
    console.log("Server is listening on port 3001. Ready to accept requests!");
});
```
Change the express port to 3001 to avoid conflict with the front end

**Review by 40thieves — APPROVED** [review]
LGTM!

**Review by fentonfentonfenton — APPROVED** [review]

**Pull request merged**
